# VirtualBox Version: 5.2.22r126460
# Vagrant Version: 2.2.6

Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.box_version = "1905.1"

	config.vm.define :target do | target |
		target.vm.hostname = "target"
		target.vm.network :private_network, ip: "192.168.111.2", virtualbox__intnet: "mynet"
	end

	config.vm.define :myeth do | myeth |
		myeth.vm.hostname = "myeth"
		myeth.vm.network :private_network, ip: "192.168.111.100", virtualbox__intnet: "mynet"
		config.vm.synced_folder "./myeth", "/code"
	end
end
